### ISSUE TITLE
Discussion section

### ISSUE THREAD

**Issue by Welsyntoffie** [hollie/tailscale-caddy-proxy#6]
Writing as issue, but would prefer a discussion section.
How would I go about exposing multiple services?
Would I just add more 
`- CADDY_TARGET=hass:8123`
`- CADDY_TARGET=grafana:3000`

**Comment by hollie** [comment]
Hey Pieter,

the way the docker system is setup is to ensure that every service has a separate hostname on the Tailscale network.

This requires a separate tailscale client for every service. 

To expose multiple services, just duplicate the docker-compose section of the tailscale client in your local setup to spin up another instance.

For your reference, please see [this ticket](https://github.com/hollie/tailscale-caddy-proxy/issues/4).

Regards,
 Lieven

**Comment by hollie** [comment]
I've enabled discussions on the project, see https://github.com/hollie/tailscale-caddy-proxy/discussions/
